name = "RapidRefreshData"
uuid = "6311d174-80ed-4991-8be9-d0557cea290a"
version = "0.0.1"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
Dates = "1.11.0"
Scratch = "1.3.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
