project:
  type: book
  output-dir: _site

engine: julia
julia:
  project: "."

book:
  title: "RapidRefreshData.jl"
  navbar:
    right:
      - icon: star
        href: https://github.com/RallypointOne/RapidRefreshData.jl/stargazers
        text: "Star"
      - icon: github
        href: https://github.com/RallypointOne/RapidRefreshData.jl
  chapters:
    - part: "Docs"
      chapters:
        - index.qmd
        - getting-started.qmd
        - api.qmd
    - part: "Reference"
      chapters:
        - changelog.qmd
        - coverage.qmd

  page-footer:
    center: "Built on __BUILD_DATE__"

format:
  html:
    css: styles.css
    number-sections: false
    theme:
      light: flatly
      dark: darkly
    include-after-body:
      - file: _version-selector.html
